name: common
description: "Package commun contenant les utilitaires partagés (Dart pur)"
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2

dependencies:
  # Injection de dépendances
  get_it: ^8.0.2
  injectable: ^2.5.0

dev_dependencies:
  test: ^1.24.0
  lints: ^5.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
