name: ui
description: "Composants UI réutilisables"
version: 0.0.1

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Dépendances aux packages domain et common
  domain:
    path: ../domain
  common:
    path: ../common
  
  # Navigation
  go_router: ^14.6.2
  
  # Injection de dépendances
  get_it: ^8.0.2
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.2
  build_runner: ^2.4.13
