# Configuration de build_runner pour le package feature_todo
targets:
  $default:
    builders:
      freezed:
        generate_for:
          - lib/src/blocs/**/*.dart
        options:
          union_key: type
          union_value_case: pascal

