name: feature_todo
description: "Feature de gestion des todos"
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Dépendances aux packages domain et common
  domain:
    path: ../domain
  common:
    path: ../common
  ui:
    path: ../ui

  # State management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  # Sérialisation
  freezed_annotation: ^2.4.4
  
  # Navigation
  go_router: ^14.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
