name: domain
description: "Couche domaine contenant les entités et use cases (Dart pur)"
version: 0.0.1
homepage:
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  # Dépendance au package common (gérée par workspace)
  common:
  
  # Utilitaires
  freezed_annotation: ^2.4.4
  
  # Injection de dépendances
  injectable: ^2.5.0

dev_dependencies:
  test: ^1.24.0
  lints: ^5.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
